
spring:
  aliyun:
    vod:
      file:
        keyid: LTAI5tAaDo7BSv7jLmCmRquz #LTAI5tAaDo7BSv7jLmCmRquz
        keysecret: ecg6N5SlHwcd5LeJqKf1I6XG44jzuj #ecg6N5SlHwcd5LeJqKf1I6XG44jzuj
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentnet
    username: root
    password: X132010546
mybatis:
  configuration:
    map-underscore-to-camel-case: true



file:
  upload-path: E:\IdeaCode\springbootReg\src\main\resources\static\coverImg\


es:
  port: 9200
  hostname: localhost